apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: ajohnson
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: harbor.dev.afsmtddso.com/ajohnson-harbor-project/db@sha256:f5a225d8a30316cf26325158ee35d234fee17c938e9fd6ca71a5c7c3a6a4fb5c
        ports: 
        - containerPort: 5432
